# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Mooos-Scraper
version:      0.01
version_from: lib/WWW/Mooos/Scraper.pm
installdirs:  site
requires:
    Class::Accessor:               0.3
    DateTime:                      0.37
    HTTP::Request:                 1.4
    LWP::UserAgent:                2.033
    Readonly:                      1.03
    Sub::Install:                  0.924
    UNIVERSAL::require:            0.11
    URI:                           1.35
    Web::Scraper:                  0.07

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
